# Generated by Django 5.2.11 on 2026-02-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(help_text='Static path or full URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bullet_one', models.CharField(max_length=200)),
                ('bullet_two', models.CharField(max_length=200)),
                ('icon_class', models.CharField(max_length=80)),
                ('accent_class', models.CharField(default='blue', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('brand_name', models.CharField(max_length=120)),
                ('brand_highlight', models.CharField(blank=True, max_length=120)),
                ('hero_badge_year', models.CharField(max_length=10)),
                ('hero_badge_text', models.CharField(max_length=200)),
                ('hero_heading_line_one', models.CharField(max_length=200)),
                ('hero_heading_highlight_one', models.CharField(max_length=200)),
                ('hero_heading_line_two', models.CharField(max_length=200)),
                ('hero_heading_highlight_two', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('primary_cta_label', models.CharField(max_length=120)),
                ('primary_cta_url', models.CharField(max_length=200)),
                ('secondary_cta_label', models.CharField(max_length=120)),
                ('secondary_cta_url', models.CharField(max_length=200)),
                ('services_title', models.CharField(max_length=200)),
                ('portfolio_title', models.CharField(max_length=200)),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_body', models.TextField()),
                ('contact_button_label', models.CharField(max_length=120)),
                ('contact_button_url', models.CharField(max_length=200)),
                ('footer_intro', models.TextField()),
                ('footer_copyright', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('color_class', models.CharField(default='text-white', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
