# Generated by Django 5.2.11 on 2026-02-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pricingpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image_path',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
