# Generated by Django 5.2.11 on 2026-03-12 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_productfaq_productpackage_productorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='client_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='delivery_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='highlight_metric',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='scope_summary',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technologies',
            field=models.TextField(blank=True, help_text='Her satıra bir teknoloji yazın'),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('request_type', models.CharField(choices=[('portal', 'Müşteri portalı'), ('web', 'Kurumsal web platformu'), ('automation', 'Operasyon otomasyonu'), ('integration', 'Entegrasyon ve API'), ('mobile', 'Mobil ve saha uygulaması'), ('consulting', 'Danışmanlık ve analiz')], max_length=30)),
                ('budget_range', models.CharField(blank=True, choices=[('not_sure', 'Henüz net değil'), ('lt_50', '50.000 TL altı'), ('50_150', '50.000 - 150.000 TL'), ('150_500', '150.000 - 500.000 TL'), ('500_plus', '500.000 TL+')], max_length=30)),
                ('timeline', models.CharField(blank=True, choices=[('urgent', '0-2 hafta'), ('month', '2-4 hafta'), ('quarter', '1-3 ay'), ('long_term', '3 ay+')], max_length=30)),
                ('project_scope', models.TextField()),
                ('systems_note', models.TextField(blank=True)),
                ('wants_portal_access', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('reviewing', 'İnceleniyor'), ('planned', 'Planlandı'), ('closed', 'Kapatıldı')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('person_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('portfolio_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='main.portfolioitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
